# ===============================
# Application
# ===============================
spring.jpa.properties.hibernate.default_schema=mdtrack

# ===============================
# Database (PostgreSQL on Render)
# ===============================
spring.datasource.url=jdbc:postgresql://dpg-d7m4i60sfn5c73dbhs20-a:5432/ps_postgres_db_j5kr?sslmode=require
spring.datasource.username=ps_postgres_db_j5kr_user
spring.datasource.password=P2r4VHlwsz0ZWdgdRLogTLjEaMMYcIvl

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Hikari (Free tier safe)
# ===============================
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initializationFailTimeout=0

