# ===============================
# Application
# ===============================
spring.jpa.properties.hibernate.default_schema=mdtrack

# ===============================
# Database (PostgreSQL on Render)
# ===============================
spring.datasource.url=jdbc:postgresql://dpg-d9ccvr61a83c73c986d0-a:5432/data_postgres_db?sslmode=require
spring.datasource.username=data_postgres_db_user
spring.datasource.password=4IgdNl7HeGZ8QLKZp2QMDN6Hc9WyQyFo

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Hikari (Free tier safe)
# ===============================
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initializationFailTimeout=0

