# ===============================
# Application
# ===============================
spring.jpa.properties.hibernate.default_schema=mdtrack

# ===============================
# Database (PostgreSQL on Render)
# ===============================
spring.datasource.url=jdbc:postgresql://dpg-d71a20tm5p6s739n69dg-a:5432/ps_postgres_db_kvu9_pu65?sslmode=require
spring.datasource.username=ps_postgres_db_kvu9_pu65_user
spring.datasource.password=UR0l9UKKdfk2X3h9NlHKdnbgFxGZizai

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Hikari (Free tier safe)
# ===============================
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initializationFailTimeout=0

